# -*- coding: utf-8 -*-
"""ml_final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqUe-GEN1g-qgS9cvEx_K-RC4RyUvqWR
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('/content/balanced_dataset.csv')

dataset = pd.read_csv('/content/dataset for ml - Form Responses 1 (1).csv')

dataset['14. Have you been diagnosed with depression?'].value_counts().plot(kind='barh')

data.drop(data.columns[0], axis=1, inplace=True)

print(data.columns)

data.isnull().sum()

# Increase the max column width to display entire content
pd.options.display.max_colwidth = None

# Increase the number of rows and columns displayed
pd.options.display.max_rows = None
pd.options.display.max_columns = None

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

one = le.fit_transform(data['1. What is your gender?'])
two = le.fit_transform(data['2. What is your age?'])
three = le.fit_transform(data['3. What is your current family situation?'])
four = le.fit_transform(data['4. What year of study are you in?'])
five_one = le.fit_transform(data['5. How much stress do you experience in the following areas of life? [Academic performance]'])
five_two = le.fit_transform(data['5. How much stress do you experience in the following areas of life? [Family relationships]'])
five_three = le.fit_transform(data['5. How much stress do you experience in the following areas of life? [Financial situation]'])
five_four = le.fit_transform(data['5. How much stress do you experience in the following areas of life? [Social life]'])
five_five = le.fit_transform(data['5. How much stress do you experience in the following areas of life? [Problems of loved ones]'])
five_six = le.fit_transform(data['5. How much stress do you experience in the following areas of life? [Workload and Examinations]'])
six = le.fit_transform(data['6. Are you involved in any extracurricular activities?'])
seven = le.fit_transform(data['7. How often do you have a drink containing alcohol'])
eight_one= le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling optimistic about the future]'])
eight_two= le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling useful]'])
eight_three= le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling relaxed]'])
eight_four= le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling able to deal with problems well]'])
eight_five= le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling able to think clearly]'])
eight_six= le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling close to others]'])
eight_seven = le.fit_transform(data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling confident]'])
nine = le.fit_transform(data['9. Which of the following best describes your sexual attraction?'])
ten_one = le.fit_transform(data['10. Please indicate how often you experience the following symptoms: [Mood Swings]'])
ten_two = le.fit_transform(data['10. Please indicate how often you experience the following symptoms: [Depressive Episodes]'])
ten_three = le.fit_transform(data['10. Please indicate how often you experience the following symptoms: [Manic Episodes]'])
eleven = le.fit_transform(data['11. How would you rank your varsity academic performance?'])
twelve = le.fit_transform(data['12. How often do you pay attention to your feelings and emotions?'])
thirteen = le.fit_transform(data['13. How often do you understand your own emotional states?'])
fourteen = le.fit_transform(data['14. Have you been diagnosed with depression?'])
fifteen = le.fit_transform(data['15. Have you ever made an attempt to take your life, by taking an overdose of tablets or in some other way?'])
sixteen = le.fit_transform(data['16. Have you ever deliberately harmed yourself in any way but not with the intention of killing yourself?'])
seventeen = le.fit_transform(data['17. Do you have a family history of mental illness?'])
eighteen = le.fit_transform(data['18. How many hours do you sleep on average per night?'])
nineteen = le.fit_transform(data['19. How do you spend your free time after University?'])
twenty_1 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling fearful]'])
twenty_2 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Nervousness or shakiness inside]'])
twenty_3 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling hopeless about the future]'])
twenty_4 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling blue]'])
twenty_5 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Worrying too much about things]'])
twenty_6 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling no interest in things]'])
twenty_7 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling everything is an effort]'])
twenty_8 = le.fit_transform(data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling worthless]'])
twenty_one = le.fit_transform(data['21. How would you describe your living environment?'])
twenty_two = le.fit_transform(data['22. How often do you go out with friends?'])

data['1. What is your gender?'] = one
data['2. What is your age?'] = two
data['3. What is your current family situation?'] = three
data['4. What year of study are you in?'] = four
data['5. How much stress do you experience in the following areas of life? [Academic performance]'] = five_one
data['5. How much stress do you experience in the following areas of life? [Family relationships]'] = five_two
data['5. How much stress do you experience in the following areas of life? [Financial situation]'] = five_three
data['5. How much stress do you experience in the following areas of life? [Social life]'] = five_four
data['5. How much stress do you experience in the following areas of life? [Problems of loved ones]'] = five_five
data['5. How much stress do you experience in the following areas of life? [Workload and Examinations]'] = five_six
data['6. Are you involved in any extracurricular activities?'] = six
data['7. How often do you have a drink containing alcohol'] = seven
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling optimistic about the future]'] = eight_one
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling useful]'] = eight_two
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling relaxed]'] = eight_three
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling able to deal with problems well]'] = eight_four
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling able to think clearly]'] = eight_five
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling close to others]'] = eight_six
data['8. Over the last two weeks, how often have you experienced the following feelings? [Feeling confident]'] = eight_seven
data['9. Which of the following best describes your sexual attraction?'] = nine
data['10. Please indicate how often you experience the following symptoms: [Mood Swings]'] = ten_one
data['10. Please indicate how often you experience the following symptoms: [Depressive Episodes]'] = ten_two
data['10. Please indicate how often you experience the following symptoms: [Manic Episodes]'] = ten_three
data['11. How would you rank your varsity academic performance?'] = eleven
data['12. How often do you pay attention to your feelings and emotions?'] = twelve
data['13. How often do you understand your own emotional states?'] = thirteen
data['14. Have you been diagnosed with depression?'] = fourteen
data['15. Have you ever made an attempt to take your life, by taking an overdose of tablets or in some other way?'] = fifteen
data['16. Have you ever deliberately harmed yourself in any way but not with the intention of killing yourself?'] = sixteen
data['17. Do you have a family history of mental illness?'] = seventeen
data['18. How many hours do you sleep on average per night?'] = eighteen
data['19. How do you spend your free time after University?'] = nineteen
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling fearful]'] = twenty_1
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Nervousness or shakiness inside]'] = twenty_2
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling hopeless about the future]'] = twenty_3
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling blue]'] = twenty_4
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Worrying too much about things]'] = twenty_5
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling no interest in things]'] = twenty_6
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling everything is an effort]'] = twenty_7
data['20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling worthless]'] = twenty_8
data['21. How would you describe your living environment?'] = twenty_one
data['22. How often do you go out with friends?'] = twenty_two

import pandas as pd
from imblearn.over_sampling import SMOTE

# Select features and target variable
Xx = data.drop(columns=['14. Have you been diagnosed with depression?'])  # Features
Yy = data['14. Have you been diagnosed with depression?']  # Target

# Apply SMOTE to balance the classes
smote = SMOTE()
X_res, y_res = smote.fit_resample(Xx, Yy)  # Correct variable names used here

# Check the new class distribution
print("Class distribution after SMOTE:")
print(pd.Series(y_res).value_counts())

# # Optionally, you can save the balanced dataset
# balanced_data = pd.DataFrame(X_res, columns=Xx.columns)  # Use Xx.columns for column names
# balanced_data['14. Have you been diagnosed with depression?'] = y_res
# balanced_data.to_csv('balanced_dataset.csv', index=False)

a = data['14. Have you been diagnosed with depression?']
b = data['10. Please indicate how often you experience the following symptoms: [Depressive Episodes]']

class_counts =a.value_counts()
class_percentages =a.value_counts(normalize=True) * 100

print("Class Counts:\n", class_counts)
print("\nClass Percentages:\n", class_percentages)

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif

features = [


        '5. How much stress do you experience in the following areas of life? [Academic performance]',
        '21. How would you describe your living environment?',
       '10. Please indicate how often you experience the following symptoms: [Mood Swings]',
       '10. Please indicate how often you experience the following symptoms: [Depressive Episodes]',
            '5. How much stress do you experience in the following areas of life? [Social life]',
'20. Over the past two weeks, how often have you experienced the following symptoms? [Feeling everything is an effort]',
            '7. How often do you have a drink containing alcohol',
             '18. How many hours do you sleep on average per night?',
            '4. What year of study are you in?',
             '12. How often do you pay attention to your feelings and emotions?',
            '20. Over the past two weeks, how often have you experienced the following symptoms? [Worrying too much about things]',
            '15. Have you ever made an attempt to take your life, by taking an overdose of tablets or in some other way?',
            '8. Over the last two weeks, how often have you experienced the following feelings? [Feeling close to others]',
             '8. Over the last two weeks, how often have you experienced the following feelings? [Feeling able to deal with problems well]',
             '22. How often do you go out with friends?',




       ]

x = data[features]
y = a

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd

# SelectKBest for feature selection
skb = SelectKBest(score_func=chi2)
sb = skb.fit(x, y)

# Create DataFrames for scores and feature names
sc = pd.DataFrame(sb.scores_, columns=['Score'])  # Ensure scores are labeled properly
sc_c = pd.DataFrame(x.columns, columns=['Feature'])  # Ensure column names are labeled properly

# Concatenate feature names and scores
res = pd.concat([sc_c, sc], axis=1)

# Sort by scores in descending order
sorted_res = res.sort_values(by='Score', ascending=False)

# Display the sorted result
print(sorted_res)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

dt = DecisionTreeClassifier()
dt.fit(xtrain, ytrain)

dt.predict(xtest)

accuracy_score(ytest, dt.predict(xtest))

print(classification_report(ytest, dt.predict(xtest)))

confusion_matrix(ytest, dt.predict(xtest))

from sklearn.ensemble import RandomForestClassifier

rc = RandomForestClassifier()
rc.fit(xtrain, ytrain)

rc.predict(xtest)

accuracy_score(ytest, rc.predict(xtest))

print(classification_report(ytest, rc.predict(xtest)))

confusion_matrix(ytest, rc.predict(xtest))

import pandas as pd

feature_importances = pd.DataFrame({'Feature': x.columns, 'Importance': rc.feature_importances_})
feature_importances = feature_importances.sort_values(by='Importance', ascending=False)
print(feature_importances.head(15))

from sklearn.svm import SVC

model = SVC(kernel='linear', random_state=0)
model.fit(xtrain, ytrain)

model.predict(xtest)

accuracy_score(ytest, model.predict(xtest))

print(classification_report(ytest, model.predict(xtest)))

confusion_matrix(ytest, model.predict(xtest))

from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression(random_state=0, max_iter=1000)

lgr.fit(xtrain, ytrain)

lgr.predict(xtest)

accuracy_score(ytest, lgr.predict(xtest))

print(classification_report(ytest, lgr.predict(xtest)))

confusion_matrix(ytest, lgr.predict(xtest))

import pandas as pd
from imblearn.over_sampling import SMOTE

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(xtrain, ytrain)

knn.predict(xtest)

accuracy_score(ytest, knn.predict(xtest))

print(classification_report(ytest, knn.predict(xtest)))

confusion_matrix(ytest, knn.predict(xtest))

from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

nb.fit(xtrain, ytrain)

nb.predict(xtest)

accuracy_score(ytest, nb.predict(xtest))

print(classification_report(ytest, nb.predict(xtest)))

confusion_matrix(ytest, nb.predict(xtest))

pip install lime

import lime
import lime.lime_tabular

lime_explainer = lime.lime_tabular.LimeTabularExplainer(training_data=np.array(xtrain), feature_names=xtrain.columns,
            class_names=['0','1'], mode='classification')

explain=lime_explainer.explain_instance(data_row=xtest.iloc[1], predict_fn=rc.predict_proba)
explain.show_in_notebook()